import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { eq } from 'drizzle-orm';
import { getDb } from '../db';
import { users, sessions, brands, channels, posts, postTargets, subscriptions } from '../db/schema';
import { ensureWorkspace } from '../lib/workspaces';
import { encryptCredentials } from '../lib/crypto';
async function main() {
  const modulePath = process.env.PLAYWRIGHT_MODULE || '/home/flori/n8n-local/node_modules/playwright/index.mjs';
  const { chromium } = await import(modulePath);
  const db = getDb(), uid = crypto.randomUUID(), token = crypto.randomUUID();
  const base = process.env.FIXER2_URL || 'http://localhost:3997';
  const evidence = process.env.FIXER2_EVIDENCE || '/home/flori/ventures2/socialmint/work/fixer2-evidence';
  mkdirSync(evidence, { recursive: true });
  const browser = await chromium.launch({ executablePath: '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
  try {
    for (const path of ['/app/billing?from=post', '/app/calendar?brand=example', '/app/posts/new?date=2026-10-01', '/app/posts/00000000-0000-0000-0000-000000000001/edit?q=x', '/app/continue?next=/pricing&plan=agency']) {
      const response = await fetch(base + path, { redirect: 'manual' });
      assert.equal(response.status, 307);
      const next = new URL(new URL(response.headers.get('location')!, base).searchParams.get('next')!, base);
      const expected = new URL(path, base);
      assert.equal(next.pathname, expected.pathname);
      assert.deepEqual([...next.searchParams], [...expected.searchParams]);
    }
    await db.insert(users).values({ id: uid, name: 'Fixer2 browser fixture' });
    const workspace = await ensureWorkspace(uid);
    await db.insert(sessions).values({ sessionToken: token, userId: uid, expires: new Date(Date.now() + 3600000) });
    await db.insert(subscriptions).values({ workspaceId: workspace.id, status: 'active', currentPeriodEnd: new Date(Date.now() + 86400000), stripeSubscriptionId: 'fixture-' + uid });
    const [brand] = await db.insert(brands).values({ workspaceId: workspace.id, name: 'Mint Studio', slug: 'fixer2', timezone: 'Europe/Berlin' }).returning();
    const [channel] = await db.insert(channels).values({ brandId: brand.id, provider: 'mastodon', displayName: 'Studio channel', externalId: 'fixture', credentialsEnc: encryptCredentials({ accessToken: 'synthetic-fixer2', instanceUrl: 'https://fixture.invalid' }), meta: { maxTextLength: 1000 } }).returning();
    const [post] = await db.insert(posts).values({ brandId: brand.id, authorUserId: uid, body: 'A little inspiration for your next creative project.', status: 'published', scheduledAt: new Date() }).returning();
    const [target] = await db.insert(postTargets).values({ postId: post.id, channelId: channel.id, status: 'published', warnings: ['One image was omitted. Add it manually.'] }).returning();
    const context = await browser.newContext({ viewport: { width: 390, height: 844 } });
    await context.addCookies([{ name: 'authjs.session-token', value: token, url: base }]);
    const page = await context.newPage();
    let pageErrors = 0;
    page.on('pageerror', () => pageErrors++);
    await page.goto(base + '/app/calendar');
    await page.getByTestId('calendar-agenda').waitFor();
    assert(await page.getByTestId('calendar-agenda').isVisible());
    assert(!(await page.getByTestId('calendar-desktop').isVisible()));
    assert.equal(await page.getByTestId('calendar-agenda').locator('section').count(), 1);
    assert(await page.getByTestId('calendar-agenda').innerText().then((text: string) => text.includes(post.body)));
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: evidence + '/calendar-390.png', fullPage: true });
    await page.setViewportSize({ width: 900, height: 900 });
    assert.equal(await page.getByTestId('calendar-desktop').locator('.grid').evaluate((el: HTMLElement) => getComputedStyle(el).gridTemplateColumns.split(' ').length), 7);
    assert(!(await page.getByTestId('calendar-agenda').isVisible()));
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(base + '/app/posts/new');
    await page.getByLabel('Post text', { exact: true }).fill('A bright idea for your next project.');
    await page.getByLabel('Studio channel', { exact: true }).check();
    // Public URL is intercepted locally; validates browser CSP without a third-party request.
    await page.route('https://images.example.org/fixture.svg', (route: { fulfill: (options: object) => Promise<void> }) => route.fulfill({ contentType: 'image/svg+xml', body: '<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200"><rect width="200" height="200" fill="#047857"/><circle cx="100" cy="100" r="60" fill="#a7f3d0"/></svg>' }));
    await page.getByText('Add image by URL', {exact:true}).click();
    await page.getByLabel('Public HTTPS image URL').fill('https://images.example.org/fixture.svg');
    await page.getByRole('button', {name:'Add image',exact:true}).click();
    await page.waitForFunction(() => { const image = document.querySelector('img[alt="Media preview 1"]') as HTMLImageElement; return image?.complete && image.naturalWidth > 0; });
    assert((await page.locator('form').filter({has: page.locator('[name=body]')}).innerText()).includes('/ 1000'));
    await page.screenshot({ path: evidence + '/composer-image-390.png', fullPage: true });
    await page.goto(base + '/app/brands/' + brand.id);
    await page.locator('[name=provider]').selectOption('mastodon');
    await page.getByLabel('Instance URL', { exact: true }).fill('http://invalid.example');
    await page.getByLabel('Access token', { exact: false }).fill('synthetic-secret');
    await page.getByRole('button', { name: 'Connect channel', exact: true }).click();
    await page.locator('form [role=alert]').waitFor();
    assert.equal(await page.locator('[name=provider]').inputValue(), 'mastodon');
    assert.equal(await page.getByLabel('Instance URL', { exact: true }).inputValue(), 'http://invalid.example');
    assert.equal(await page.getByLabel('Access token', { exact: false }).inputValue(), 'synthetic-secret');
    await page.screenshot({ path: evidence + '/connect-error-390.png', fullPage: true });
    await page.goto(base + '/app/posts/' + post.id);
    await page.getByText('Published with warnings', { exact: true }).waitFor();
    assert((await page.locator('main').innerText()).includes('Add it manually'));
    await page.screenshot({ path: evidence + '/warnings-390.png', fullPage: true });
    await db.update(subscriptions).set({ status: 'canceled' }).where(eq(subscriptions.workspaceId, workspace.id));
    await page.goto(base + '/app/posts/new');
    assert(await page.getByRole('button', { name: 'Schedule', exact: true }).isDisabled());
    assert(!(await page.getByRole('button', { name: 'Save draft', exact: true }).isDisabled()));
    await page.getByLabel('Post text', { exact: true }).fill('Draft while subscription is inactive');
    await page.getByRole('button', { name: 'Save draft', exact: true }).click();
    await page.waitForURL(/\/app\/posts\/[a-f0-9-]+$/);
    await db.update(postTargets).set({ status: 'needs_review', lastErrorCode: 'UNCERTAIN' }).where(eq(postTargets.id, target.id));
    await db.update(posts).set({ status: 'failed' }).where(eq(posts.id, post.id));
    await page.goto(base + '/app/posts/' + post.id);
    assert(await page.getByRole('button', { name: 'Retry now', exact: true }).isDisabled());
    await db.update(subscriptions).set({ status: 'active' }).where(eq(subscriptions.workspaceId, workspace.id));
    await page.reload();
    await page.getByRole('button', { name: 'Retry now', exact: true }).click();
    await page.getByText('Retry requested', { exact: true }).waitFor();
    const retried = (await db.select().from(postTargets).where(eq(postTargets.id, target.id)))[0];
    assert.equal(retried.status, 'queued'); assert.equal(retried.attempts, 0);
    await db.update(sessions).set({ expires: new Date(Date.now() - 1000) }).where(eq(sessions.sessionToken, token));
    const expiredPath = '/app/calendar?brand=' + brand.id;
    const expired = await fetch(base + expiredPath, { redirect: 'manual', headers: { cookie: 'authjs.session-token=' + token } });
    assert.equal(expired.status, 307);
    assert.equal(new URL(expired.headers.get('location')!, base).searchParams.get('next'), expiredPath);
    assert.equal(pageErrors, 0);
    writeFileSync(evidence + '/browser-results.json', JSON.stringify({ mobileAgendaDays: 1, desktopColumns: 7, externalImageLoaded: true, providerAndValuesPreserved: true, secretPreservedAfterError: true, warningsVisible: true, inactiveDraftAllowed: true, retryGatedAndManualReset: true, redirectPathsPreserved: 5, expiredSessionPathPreserved: true, pageErrors }, null, 2));
    console.log('PASS: 390px agenda, 7 desktop columns, external-image CSP, connect-error state, warnings, canceled billing/drafts/retry, 5 exact login destinations');
  } finally { await browser.close(); await db.delete(users).where(eq(users.id, uid)); await db.$client.end(); }
}
main().catch(error => { console.error('Browser verification failed', error.name, error.message); process.exitCode = 1; });
