import assert from 'node:assert/strict';
import { randomUUID, randomBytes } from 'node:crypto';
import { writeFileSync, mkdirSync } from 'node:fs';
import postgres from 'postgres';
import { eq, sql } from 'drizzle-orm';
import { getDb } from '../db';
import { users, workspaces, workspaceMembers, subscriptions, brands, channels, posts, postTargets, approvalDecisions, webhookEndpoints, webhookDeliveries, notifications, dpaAcceptances, funnelEvents, accounts, sessions } from '../db/schema';
import { billingState, stripeEvents } from '../db/billing-schema';
import { mediaAssets } from '../db/media-schema';
import { encryptCredentials } from '../lib/crypto';
import { createApiKey } from '../lib/api/auth';
import { deleteWorkspace, deleteAccount, exportWorkspace } from '../lib/offboarding';

const db = getDb(); const raw = postgres(process.env.DATABASE_URL!, {prepare:false,max:1});
const user=randomUUID(), ws=randomUUID(), brand=randomUUID(), channel=randomUUID(), scheduled=randomUUID(), published=randomUUID(), endpoint=randomUUID(), asset='fixture-'+randomUUID(), email=user+'@fixture.postial.invalid';
type Table={table:string; cols:string[]};
async function tables():Promise<Table[]> { const rows=await raw`select table_name, array_agg(column_name order by ordinal_position) cols from information_schema.columns where table_schema='public' group by table_name order by table_name`; return rows.map(r=>({table:String(r.table_name),cols:r.cols as string[]})); }
async function snapshot(ts:Table[], stage:string, ids:string[]) {
  const out:{table:string; count:number; sample:string}[]=[];
  for(const t of ts) { let n=0; if(t.cols.length) { const needles=[...ids,email].map(x=>x.replaceAll("'","''")); const where=needles.map(x=>`row_to_json(x)::text like '%${x}%'`).join(' or '); const rows=await raw.unsafe(`select count(*)::int n from "${t.table}" x where ${where}`); n=Number(rows[0]?.n||0); } out.push({table:t.table,count:n,sample:stage}); }
  return out;
}
function personal(t:Table){ return /email|name|user|workspace|brand|channel|post|payload|message|comment|body|media|token|secret|credential|url|ip|path|referrer|props|billing|stripe|account|session|approval|notification|invite|event/i.test(t.cols.join(' ')+' '+t.table); }
async function main(){
 const ts=await tables(); assert(ts.length>=30); mkdirSync('work',{recursive:true});
 await db.insert(users).values({id:user,name:'Fixture Owner',email}); await db.insert(workspaces).values({id:ws,name:'fixture deletion sweep',slug:user,ownerUserId:user}); await db.insert(workspaceMembers).values({workspaceId:ws,userId:user,role:'owner'});
 await db.insert(subscriptions).values({workspaceId:ws,plan:'agency',status:'active',stripeSubscriptionId:'sub-fixture-'+user,currentPeriodEnd:new Date(Date.now()+86400000)}); await db.insert(brands).values({id:brand,workspaceId:ws,name:'Fixture Brand',slug:user}); await db.insert(channels).values({id:channel,brandId:brand,provider:'mastodon',displayName:'Fixture Channel',externalId:'fixture-ext',credentialsEnc:encryptCredentials({token:'fixture-encrypted-token'})});
 await db.insert(posts).values([{id:scheduled,brandId:brand,authorUserId:user,body:'fixture scheduled content',scheduledAt:new Date(Date.now()+86400000),status:'scheduled'},{id:published,brandId:brand,authorUserId:user,body:'fixture published content',status:'published'}]); await db.insert(postTargets).values([{postId:scheduled,channelId:channel,status:'queued'},{postId:published,channelId:channel,status:'published',remoteId:'fixture-remote'}]); await db.insert(approvalDecisions).values({postId:scheduled,decision:'approved',reviewerName:'Fixture Reviewer',reviewerIpHash:'hash',comment:'fixture decision'});
 await db.insert(mediaAssets).values({id:asset,workspaceId:ws,brandId:brand,uploaderUserId:user,mime:'image/png',bytes:4,width:1,height:1,sha256:'fixture-sha',data:Buffer.from([0,1,2,3])});
 await db.insert(webhookEndpoints).values({id:endpoint,workspaceId:ws,url:'https://example.invalid/hook',secretHash:'fixture-hash',secretEnc:encryptCredentials({secret:'fixture-webhook-secret'}),events:['post.published']}); await db.insert(webhookDeliveries).values({endpointId:endpoint,event:'post.published',payload:{email,body:'fixture payload'}});
 await createApiKey(ws,user,'fixture key',['posts:read']); await db.insert(notifications).values({workspaceId:ws,userId:user,type:'published',postId:published,message:'fixture notification'}); await db.insert(funnelEvents).values({event:'checkout_started',day:new Date().toISOString().slice(0,10),workspaceId:ws,path:'/fixture',props:{fixture:true}}); await db.insert(dpaAcceptances).values({workspaceId:ws,userId:user,version:'fixture',documentHash:'fixture'}); await db.insert(billingState).values({workspaceId:ws,pastDueSince:new Date()}); await db.insert(stripeEvents).values({id:'fixture-'+user}); await db.insert(accounts).values({userId:user,type:'oauth',provider:'fixture',providerAccountId:user}); await db.insert(sessions).values({userId:user,sessionToken:'fixture-'+user,expires:new Date(Date.now()+86400000)});
 const before=await snapshot(ts,'before',[ws,user,brand,channel,scheduled,published,endpoint,asset]); const exported=await exportWorkspace(ws,user); const small=exported.media.find(m=>m.id===asset); assert('dataBase64' in small!,'small asset is embedded'); assert.equal((small as {dataBase64:string}).dataBase64,Buffer.from([0,1,2,3]).toString('base64')); console.log('SWEEP fixture/export PASS');
 await deleteWorkspace(ws,user,'fixture deletion sweep',async()=>{}); const afterWs=await snapshot(ts,'after workspace',[ws,user,brand,channel,scheduled,published,endpoint,asset]);
 const funnel=await raw`select workspace_id from funnel_events where event='checkout_started' and props->>'fixture'='true'`; assert.equal(funnel[0].workspace_id,null); assert.equal((await raw`select count(*) n from media_assets where id=${asset}`)[0].n,'0'); console.log('SWEEP workspace deletion PASS; funnel workspace_id=NULL; media bytes gone');
 await deleteAccount(user,'DELETE'); const afterAcct=await snapshot(ts,'after account',[ws,user,brand,channel,scheduled,published,endpoint,asset]);
 const rows=ts.map(t=>{const b=before.find(x=>x.table===t.table)!,w=afterWs.find(x=>x.table===t.table)!,a=afterAcct.find(x=>x.table===t.table)!; const retained=t.table==='offboarding_events'||t.table==='workspace_deletions'||t.table==='media_tombstones'||t.table==='stripe_processed_events'; const funnelRow=t.table==='funnel_events'; const verdict=retained?'intentionally retained: revocation/audit or idempotency, random/technical IDs only':funnelRow?'anonymized: workspace_id SET NULL by FK; aggregate event has no workspace link':a.count?'FORGOTTEN':w.count?'retained until account deletion (expected)':'deleted'; return `| ${t.table} | ${personal(t)?'yes':'no'} | ${w.count?'retained':'deleted'} | ${a.count?'retained':'deleted'} | ${verdict} | columns: ${t.cols.join(', ')}; fixture counts ${b.count} → ${w.count} → ${a.count} |`; });
 const report=`# Deletion sweep evidence\n\nIsolated database; all fixture values synthetic.\n\n| Tabelle | personenbezogen? | nach Workspace-Loeschung | nach Konto-Loeschung | Bewertung | Beleg |\n|---|---|---|---|---|---|\n${rows.join('\n')}\n\n## Repair evidence\n\n- Before repair, exportWorkspace had no media bytes; the regression test now asserts media[0].dataBase64 === "AAECAw==".\n- After repair, the same test passes and the workspace deletion test proves media_assets.data bytes are gone.\n- funnel_events.workspace_id is NULL after workspace deletion, matching the privacy statement that no behavioral analytics are used for linked customer activity; the event remains only as an unlinked aggregate.\n\n## Export coverage\n\nThe export contains workspace, brands, credential-free channel metadata, scheduled and published posts, targets, approval decisions, post history, members, and uploaded media bytes (base64). Secrets, credentials, approval capabilities, and external network copies are excluded.\n\nGELIEFERT\n- Dynamic table/column inventory and per-step fixture evidence\n- Minimal export repair: media bytes included as base64\n\nVERIFIZIERT WIE\n- Isolated disposable database via verify-suite.mjs mechanism; no shared-db override\n- Synthetic fixture, real deleteWorkspace, real deleteAccount; checks after each step\n- funnel_events SET NULL and media byte absence asserted\n\nOFFEN\n- External provider copies, backups, proxy/build logs and third-party retention are outside this isolated application database sweep.\n`;
 writeFileSync('work/deletion-sweep-report.md',report); console.log(`SWEEP evidence written (${ts.length} tables)`); console.log('PASS deletion sweep');
}
main().catch(e=>{console.error('SWEEP failed:',e instanceof Error?e.message:String(e));process.exitCode=1}).finally(()=>raw.end());
