import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { and, eq, inArray } from 'drizzle-orm';
import { getDb } from '../db';
import { users, sessions, workspaces, workspaceMembers, workspaceInvites, subscriptions } from '../db/schema';
import { ensureWorkspace } from '../lib/workspaces';
import { manageTeam, acceptInvite, findInvite, inviteProblem } from '../lib/team';
async function main() {
  const db = getDb(), owner = crypto.randomUUID(), editor = crypto.randomUUID(), other = crypto.randomUUID();
  const ownerSession = crypto.randomUUID(), editorSession = crypto.randomUUID();
  const base = process.env.TEAM_HTTP_URL ?? 'http://localhost:3997';
  let browser: { close(): Promise<void> } | undefined;
  try {
    await db.insert(users).values([{ id: owner, name: 'Team Owner', email: `${owner}@example.invalid` }, { id: editor, name: 'Team Editor', email: `${editor}@example.invalid` }, { id: other, name: 'Another Member' }]);
    const ws = await ensureWorkspace(owner), second = await ensureWorkspace(editor);
    await db.update(workspaces).set({ name: 'Team verification' }).where(eq(workspaces.id, ws.id));
    await assert.rejects(manageTeam(ws.id, owner, 'create'), /Seat limit/);
    await assert.rejects(manageTeam(ws.id, owner, 'remove', owner), /yourself/);
    await assert.rejects(manageTeam(ws.id, owner, 'role', owner, 'editor'), /one owner/);
    await db.insert(subscriptions).values({ workspaceId: ws.id, plan: 'agency', status: 'active', stripeSubscriptionId: `sub_team_${owner}`, currentPeriodEnd: new Date(Date.now() + 86400000) });
    await db.insert(sessions).values([{ sessionToken: ownerSession, userId: owner, expires: new Date(Date.now() + 3600000) }, { sessionToken: editorSession, userId: editor, expires: new Date(Date.now() + 3600000) }]);
    const token = (await manageTeam(ws.id, owner, 'create'))!;
    const publicResponse = await fetch(`${base}/join/${token}`); assert.equal(publicResponse.status, 200); assert.match(await publicResponse.text(), /Sign in to join/);
    const mod = process.env.PLAYWRIGHT_MODULE ?? '/home/flori/n8n-local/node_modules/playwright/index.mjs';
    const { chromium } = await import(mod);
    const b = await chromium.launch({ headless: true, executablePath: '/usr/bin/google-chrome', args: ['--no-sandbox'] }); browser = b;
    const ownerContext = await b.newContext();
    await ownerContext.addCookies([{ name: 'authjs.session-token', value: ownerSession, url: base }]);
    const page = await ownerContext.newPage();
    const editorContext = await b.newContext();
    await editorContext.addCookies([{ name: 'authjs.session-token', value: editorSession, url: base }]);
    const join = await editorContext.newPage();
    await mkdir('work/team-evidence', { recursive: true });
    for (const width of [390, 1280]) {
      await page.setViewportSize({ width, height: 900 }); await page.goto(`${base}/app/settings/team`); await page.getByRole('heading', { name: 'Team', exact: true }).waitFor();
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
      await page.screenshot({ path: `work/team-evidence/team-${width}.png`, fullPage: true });
      await join.setViewportSize({ width, height: 900 }); await join.goto(`${base}/join/${token}`); await join.getByRole('button', { name: 'Join workspace' }).waitFor();
      await join.screenshot({ path: `work/team-evidence/join-${width}.png`, fullPage: true });
    }
    await page.getByRole('button', { name: 'Create invite link' }).click();
    const linkInput = page.getByRole('textbox', { name: 'Invite link' });
    await linkInput.waitFor();
    const uiLink = await linkInput.inputValue();
    assert(uiLink.startsWith(base + '/join/'));
    assert(await findInvite(uiLink.split('/').pop()!));
    await page.reload();
    assert.equal(await page.getByRole('textbox', { name: 'Invite link' }).count(), 0);
    await join.getByRole('button', { name: 'Join workspace' }).click(); await join.waitForURL(`${base}/app`);
    const [membership] = await db.select().from(workspaceMembers).where(and(eq(workspaceMembers.workspaceId, ws.id), eq(workspaceMembers.userId, editor))); assert.equal(membership.role, 'editor');
    assert.match(inviteProblem((await findInvite(token))?.invite)!, /already been used/);
    assert.equal((await ensureWorkspace(editor, ws.id)).id, ws.id);
    assert.equal((await ensureWorkspace(editor, second.id)).id, second.id);
    assert.equal((await db.select().from(workspaces).where(eq(workspaces.ownerUserId, editor))).length, 1);
    const billing = await editorContext.request.post(`${base}/api/stripe/portal`, { headers: { origin: base } }); assert.equal(billing.status(), 403);
    await join.goto(`${base}/app/settings/api`); assert.match(await join.locator('body').innerText(), /Only the workspace owner/);
    await join.goto(`${base}/app/settings/team`); assert.match(await join.locator('body').innerText(), /Only owners/);
    await join.getByRole('combobox', { name: 'Workspace', exact: true }).first().selectOption(second.id); await join.getByRole('button', { name: 'Switch workspace' }).first().click(); await join.waitForURL(`${base}/app`);
    assert.equal((await editorContext.cookies()).find((c: { name: string }) => c.name === 'sm_ws')?.value, second.id);
    const expired = (await manageTeam(ws.id, owner, 'create'))!;
    await db.update(workspaceInvites).set({ expiresAt: new Date(0) }).where(eq(workspaceInvites.id, (await findInvite(expired))!.invite.id));
    assert.match(await (await fetch(`${base}/join/${expired}`)).text(), /has expired/); await assert.rejects(acceptInvite(expired, other), /expired/);
    const revoked = (await manageTeam(ws.id, owner, 'create'))!; await manageTeam(ws.id, owner, 'revoke', (await findInvite(revoked))!.invite.id);
    assert.match(await (await fetch(`${base}/join/${revoked}`)).text(), /was revoked/); await assert.rejects(acceptInvite(revoked, other), /revoked/);
    await assert.rejects(manageTeam(ws.id, editor, 'create'), /Only owners/);
    await manageTeam(ws.id, owner, 'role', editor, 'owner'); await manageTeam(ws.id, editor, 'role', owner, 'editor');
    await manageTeam(ws.id, editor, 'role', owner, 'owner'); await manageTeam(ws.id, owner, 'role', editor, 'editor');
    await manageTeam(ws.id, owner, 'remove', editor);
    assert.equal((await db.select().from(workspaceMembers).where(and(eq(workspaceMembers.workspaceId, ws.id), eq(workspaceMembers.userId, editor)))).length, 0);
    const concurrent = (await manageTeam(ws.id, owner, 'create'))!;
    const attempts = await Promise.allSettled([acceptInvite(concurrent, editor), acceptInvite(concurrent, other)]);
    assert.equal(attempts.filter(r => r.status === 'fulfilled').length, 1);
    const already = attempts[0].status === 'fulfilled' ? editor : other;
    const unused = (await manageTeam(ws.id, owner, 'create'))!;
    await assert.rejects(acceptInvite(unused, already), /already a member/);
    await db.update(subscriptions).set({ plan: 'starter' }).where(eq(subscriptions.workspaceId, ws.id));
    await assert.rejects(acceptInvite(unused, already === editor ? other : editor), /seat limit/);
    await db.update(subscriptions).set({ plan: 'agency' }).where(eq(subscriptions.workspaceId, ws.id));
    for (let i = 6; i < 10; i++) await manageTeam(ws.id, owner, 'create');
    await assert.rejects(manageTeam(ws.id, owner, 'create'), /Invite limit/);
    console.log('PASS team: browser join, editor billing 403, settings guards, roles, seats, expiry, revocation, removal, last owner, rate limit, workspace cookie/context, 390/1280 screenshots');
  } finally { await browser?.close(); await db.delete(users).where(inArray(users.id, [owner, editor, other])); await db.$client.end(); }
}
main().catch(e => { console.error(e instanceof Error ? e.message : 'Team verification failed'); process.exitCode = 1; });
